### ISSUE TITLE
deleting app via UI not working

### ISSUE THREAD

**Issue by derekschultz** [fnproject/ui#28]
Tested locally:
1. created app via CLI
1. tried to delete app via UI (no action and nothing in container logs)
1. repeated above using _only_ the UI, and same result

![functions ui 2017-11-14 10-50-58](https://user-images.githubusercontent.com/1816629/32795737-daa71532-c929-11e7-8ae8-6fa896d5f122.png)

**Comment by carimura** [comment]
this works now
