### ISSUE TITLE
Create separate Vue component for Graph legend

### ISSUE THREAD

**Issue by nigeldeakin** [fnproject/ui#40]
Currently the legend above each graph is constructed using the following code in `client/graphUtilties.js` (function `updateChart`):

```
     // now examine the data that the graph is displaying and use it to construct the legend  
    var legs = document.getElementById(graphLegendDivName);
    var text = [];
    text.push('<ul class=\'' + 'chartLegend\'>');
    var chartDataDatasets = chart.datacollection["datasets"];
    var chartDataDatasetsLength = chartDataDatasets.length;
    for (var i = 0; i < chartDataDatasets.length; i++) {
      text.push('<li><span class=\'chartLabelEmblem\' style=\'' +
        'background-color:' + chartDataDatasets[i].backgroundColor + '; ' +
        'border-color:' + chartDataDatasets[i].borderColor + ';' +
        '\'></span>');
      if (chartDataDatasets[i].label) {
        text.push('<span class=\'chartLabelText\'>'+chartDataDatasets[i].label+'</span>');
      }
      text.push('</li>');
    }
    text.push('</ul>');
    if (legs!=null){
      legs.innerHTML  = text.join(''); 
    }
```
This application is built using the Vue framework, and modifying the DOM directly by setting `innerHTML` is frowned upon. One reviewer of this code described it as an "antipattern". The above code is also rather hard to read and understand. 

This part of the UI should be encapsulated as a Vue component rather than by changing the DOM  directly.

**Comment by vzDevelopment** [comment]
I've made a commit for this above.

It seems to be a little slower (I think it's just where Vue needs to realise it needs to update itself), but other than that it seems to work well.
