### ISSUE TITLE
ui not working the v2 api

### ISSUE THREAD

**Issue by itsmurugappan** [fnproject/ui#52]
i update the fn api server today and the ui stopped working with 404 error.

**Comment by Daniel-Dos** [comment]
I'm getting the same error as the image:

![erro](https://user-images.githubusercontent.com/8139890/45993483-9f33c480-c065-11e8-845c-22ba33e11a19.png)


![error2](https://user-images.githubusercontent.com/8139890/45993488-a3f87880-c065-11e8-8d2e-9d245c873938.png)

**Comment by rkhunter** [comment]
yeap...

**Comment by deepak-chirammel** [comment]
Previously when I used it, i.e., when the Fn was using the routes approach, the Fn UI was working fine.
But after the recent Fn Server upgrade (after the trigger approaches), the Fn UI stopped working. Is there a quick solution for it?

**Comment by Daniel-Dos** [comment]
Hi ,

until now no , but has report of issue about he -> 

https://github.com/fnproject/fn/issues/1258

**Comment by rikgibson** [comment]
Hi folks, we do understand the issues around the UI and it's lack of compatibility with the new V2 API.  It's not a quick fix and we don't have any people available with the right front-end skills to take it on.  If any of you are up for it we'd be very happy to have some help!

**Comment by vzDevelopment** [comment]
I've done a bit of work towards this, but there's still lots to do.

The changes I've made above get the creating/editing/deletion of apps back up and running. Some of the things still left to do are as follows:

* Add support for deleting config values - we need to set value to empty in order for the API to realise it needs to remove it.
* Add support for managing `syslog_url` and `annotations` for apps.
* Delete the app routes logic - I don't think this is used any more.
* Get the individual App page working - currently the deprecated app routes are breaking it.
* Get function running back up and working - currently it's trying to use routes but these no longer exist.
* Get metrics working.
* Test authentication.
* Link to the new FN API docs.
* Add support for any new functionality.
* Get the UI working with the latest node modules.

**Comment by vzDevelopment** [comment]
I have code for this:

> Delete the app routes logic - I don't think this is used any more.
> Get the individual App page working - currently the deprecated app routes are breaking it.
> Get function running back up and working - currently it's trying to use routes but these no longer exist.

Which I'll be pushing shortly. I acheived this by just adapting the current `routes` logic to use the `fns` logic/API instead.

I've also fixed the app switching logic which I missed from my previous commit. As my previous commit hasn't been reviewed yet I may force push so it's included with the previous changes.

A few other things that I noticed need doing:
* Change the docker image to use `webpack@^1.14.0` to get it working again (it's currently breaking for the same reasons as in #55).
* Add support for managing annotations for functions.
* Lint the code - e.g. be consistent with the use of semi colons and remove trailing whitespace.

**Comment by vzDevelopment** [comment]
The latest commits above (c.f. [this branch](https://github.com/vzDevelopment/ui/commits/bugfix/52-fix_metrics)) fix the charts.

The metrics it was using from the fnserver e.g. `fn_completed` are no longer broken down per app/function so I originally changed the code to just show these charts on the main page. However, I then noticed app/fn metrics were added in fnproject/fn#1365 so I added the charts back on the detailed apps page and changed the code to use these new metrics instead.

I'm not convinced these app/fn metric graphs are going to scale well e.g. when there are lots of apps/functions it has to plot, but we'll see. I've done a bit of refactoring making them easy to add/remove so we can easily remove them if they cause issues.

The things left on the todo list (apart from updating the node modules) should be relatively straight forward. They are:

* Link to the new FN API docs.
* Fix FN Logo homepage link - it's not going back to the home page.
* Add support for deleting config values - we need to set value to empty in order for the API to realise it needs to remove it.
* Add support for managing `syslog_url` and `annotations` for apps.
* Add support for managing `annotations` for functions.
* Test authentication.
* Get the UI working with the latest node modules.
* Lint the code - e.g. be consistent with the use of semi colons and remove trailing whitespace.
* Add support for any new functionality.

I'm hoping to take a look at these after the easter break.

**Comment by vzDevelopment** [comment]
I have commits for:

>* Link to the new FN API docs.
> * Fix FN Logo homepage link - it's not going back to the home page.
> * Add support for deleting config values - we need to set value to empty in order for the API to realise it needs to remove it.
> * Add support for managing syslog_url

I've created a separate PR for the first two as these are independent of any other changes I've made.

However, the latter two are dependant on https://github.com/fnproject/ui/pull/58/commits/a188cfb99c81c44864e6bcd0d9fa61cc8fba04c7 which is currently pending review in #58. I'll wait for it to be reviewed before raising PRs for these.

**Comment by carimura** [comment]
thanks @vzDevelopment going to close this issue now that the major PR's are merged!
