### ISSUE TITLE
Dev setup instructions result in errors

### ISSUE THREAD

**Issue by vzDevelopment** [fnproject/ui#55]
Following the current dev instructions:

```
npm install
sudo npm install -g webpack
webpack
```

Results in errors preventing developers from getting a working dev system up and running. The reason why is because the `npm install -g webpack` command will install the latest version of webpack e.g. 3/4. However, everything else needs to be updated accordingly which will take quite a bit of time to do. For now, we could just change the instructions to `npm install -g webpack@^1.14.0`. At least this way developers that want to work on it can get something working up and running.

For reference, the errors following the current instructions are as follows:

Running webpack will ask you to install the `webpack-cli`:
```
vzarola-Mac:ui vzarola$ webpack
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): yes
...
+ webpack-cli@3.3.0
```

Running webpack after this, will cause it to complain that it can't find it:
```
{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at runCommand.then (/usr/local/lib/node_modules/webpack/bin/webpack.js:143:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
```

I think this is because it needs installing globally to match the global install of webpack. However, after doing this it still errors:

```
vzarola-Mac:ui vzarola$ webpack
/private/tmp/ui/ui/node_modules/webpack-cli/bin/cli.js:231
				throw err;
				^

TypeError: validateSchema is not a function
```

I went on a wild goosechase trying to fix this (updating various packages and updating the code to remove deprecated functionality), but it was taking too long so I decided to just install the older version for now.

**Comment by vzDevelopment** [comment]
I've also updated the Dockerfile so that when the docker image is built it uses a working webpack version. I've added this to the previous commit as it makes sense to me for them to be together.

**Comment by rdallman** [comment]
think this is closed now? thanks

**Comment by vzDevelopment** [comment]
Yup. Confirmed with:

```
vzarola-Mac:ui vzarola$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
vzarola-Mac:ui vzarola$ docker build -t fnui .

```

Thanks, Reed 😄
