### ISSUE TITLE
delete func config vars from UI currently not working

### ISSUE THREAD

**Issue by carimura** [fnproject/ui#63]

**Comment by carimura** [comment]
The PUT seems to work properly (removes the config param I'm trying to delete) ... but doesn't actually remove config.

**Comment by vzDevelopment** [comment]
Hi @carimura, I've just checked on a clean version of master and it's working for me. For example:

I create an app ui app with two configs:
```
vzarola-Mac:~ vzarola$ fn inspect app uiapp
{
	"config": {
		"aConfigVar": "var1",
		"aConfigVar2": "var2"
	},
	"created_at": "2019-04-25T18:18:02.687Z",
	"id": "01D9AVFZHZNG8G00GZJ0000001",
	"name": "uiapp",
	"updated_at": "2019-04-25T18:18:02.687Z"
}
```

I then deleted one of the configs using the UI and got
```
vzarola-Mac:~ vzarola$ fn inspect app uiapp
{
	"config": {
		"aConfigVar2": "var2"
	},
	"created_at": "2019-04-25T18:18:02.687Z",
	"id": "01D9AVFZHZNG8G00GZJ0000001",
	"name": "uiapp",
	"updated_at": "2019-04-25T18:18:31.102Z"
}
```

Do you have any more info so I can try and replicate? Does the issue happen with both apps and functions?

**Comment by carimura** [comment]
oh i see it's supposed to send an empty val. Ya I don't see that.. per screenshot below, the config var I was deleting was a:b

![Screen Shot 2019-04-25 at 11 19 22 AM](https://user-images.githubusercontent.com/92664/56758718-2e17d500-674c-11e9-85a1-1030eefd46b7.png)

**Comment by vzDevelopment** [comment]
Humm I can't seem to replicate the issue (just tried with a function using `a => b`, `c => d` and deleting `a => b`. Have you tried running webpack again? Maybe something went wrong with the build. Are there any errors in the console at all?

Created a function using the UI:
```
vzarola-Mac:~ vzarola$ fn inspect function uiapp hello
{
	"annotations": {
		"fnproject.io/fn/invokeEndpoint": "http://localhost:8080/invoke/01D9AW09QVNG8G00GZJ0000002"
	},
	"app_id": "01D9AVFZHZNG8G00GZJ0000001",
	"config": {
		"a": "b",
		"c": "d"
	},
	"created_at": "2019-04-25T18:26:57.403Z",
	"id": "01D9AW09QVNG8G00GZJ0000002",
	"idle_timeout": 30,
	"image": "fnproject/hello",
	"memory": 128,
	"name": "hello",
	"timeout": 30,
	"updated_at": "2019-04-25T18:29:54.089Z"
}
```
After deleting `a => b`
```
vzarola-Mac:~ vzarola$ fn inspect function uiapp hello
{
	"annotations": {
		"fnproject.io/fn/invokeEndpoint": "http://localhost:8080/invoke/01D9AW09QVNG8G00GZJ0000002"
	},
	"app_id": "01D9AVFZHZNG8G00GZJ0000001",
	"config": {
		"c": "d"
	},
	"created_at": "2019-04-25T18:26:57.403Z",
	"id": "01D9AW09QVNG8G00GZJ0000002",
	"idle_timeout": 30,
	"image": "fnproject/hello",
	"memory": 128,
	"name": "hello",
	"timeout": 30,
	"updated_at": "2019-04-25T18:30:05.803Z"
}
```

**Comment by vzDevelopment** [comment]
Here's a screenshot of Firefox's debug tools when I click save after deleting a config for a function:

<img width="1428" alt="Screen Shot 2019-04-25 at 19 34 30" src="https://user-images.githubusercontent.com/49067415/56759667-6097f100-6791-11e9-8462-9b38df47db76.png">

**Comment by carimura** [comment]
wait. i think this is user error again. My webpack was failing thus I wasn't testing latest. one sec

**Comment by carimura** [comment]
yep. mea culpa. we're good!!

**Comment by vzDevelopment** [comment]
Wooo. You had me worried for a second then - thought I'd missed something 😅
