### ISSUE TITLE
Api responded with ECONNREFUSED undefined

### ISSUE THREAD

**Issue by muhammadhanif** [fnproject/ui#73]
Condition:
- Fn Server is running on port 8080

I have deployed [UI for Fn](https://github.com/fnproject/ui) using docker. 

```
docker run --rm -it --link fnserver:api -p 4000:4000 -e "FN_API_URL=http://localhost:8080" fnproject/ui
```

But I got a problem:

```
> FunctionsUI@0.0.37 start /app
> node server

WARNING: NODE_ENV value of 'production' did match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
info: Using API url: localhost:8080
info: Server running on port 4000
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
error: Error. Api responded with  ECONNREFUSED undefined
```
When I access the portal (http://localhost:4000/#/), a notification appears: `Something went terribly wrong (Status Code: 0)`

**Comment by vzDevelopment** [comment]
What happens if you use:

```
docker run --rm -it --link fnserver:api -p 4000:4000 -e "FN_API_URL=http://api:8080" fnproject/ui
```

Instead?

Notice the `api:8080` vs `localhost:8080` in the `FN_API_URL`

**Comment by muhammadhanif** [comment]
> Hi muhammadhanif,
> 
> Thank you for your interest in the fnproject.
> 
> With regards to your question, try using this instead:
> 
> ```
> docker run --rm -it --link fnserver:api -p 4000:4000 -e "FN_API_URL=http://api:8080" fnproject/ui
> ```
> 
> Notice the `api:8080` vs `localhost:8080` in the `FN_API_URL`.
> 
> I'm expecting this is just a typo/oversight but for those that come across this and don't see what's wrong, it's because the `FN_API_URL` needs to point to the fnserver docker container (which you specify in `--link`). Currently it's pointing to port 8080 on the UI container where nothing is listening which is why it's giving the connection refused error.

Hi vzDevelopment, 

Thank you for your clear explanation. It works.
```
docker run --rm -it --link fnserver:api -p 4000:4000 -e "FN_API_URL=http://api:8080" fnproject/ui
```
Yes, it's just a typo and it's my fault :D.
